@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(client, Client, "HTTP client")
System_Boundary(c1, "Schema film and report service") {
Container(film_service, "Film Service", "Golang", "Film data processing service", $tags = "microService")
ContainerDb(film_db, "Film Database", "MongoDB", "Storage Film", $tags = "storage")
ContainerQueue(queue_service, "Queue", "Redis", "Using for send messages")
Container(report_service, "Report Service", "Golang", "Report data processing service", $tags = "microService")
ContainerDb(report_db, "Report Database", "MongoDB", "Storage Report", $tags = "storage")
}

Rel(client, film_service, "HTTP Request")
Rel(film_service, film_db, "SQL Request")
Rel(film_db, film_service, "Response")
Rel(film_service, queue_service, "Async push messages")
Rel(queue_service, report_service, "Async push messages")
Rel(report_service, report_db, "SQL Request")
Rel(report_db, report_service, "Repsonse")

@enduml
