@startuml

header Example sequence diagram
title __"Communication film and report service"__

autonumber
autoactivate on

participant "HTTP Client" as ma
participant "Film-web service" as fs
database "Film database" as fdb
queue "Redis queue" as rq
participant "Report service" as rs
database "Report database" as rdb

ma -[#Red]-> fs : Request
note left
[POST] /api/v1/send-reports
end note
fs -[#Red]-> fdb : Request
fdb --[#Red]-> fdb : Response
fdb --[#Red]-> fs : Response [200 ok]
alt "Data not found"
fdb --[#Red]-> fs : Response [404 ok]
end alt

loop "Looping requests"
fs -[#Blue]->> rq : Request
end
rq --[#Blue]->> rs : Request
rs --[#Blue]-> rdb : Request
note left
[POST] /api/v1/create-reports
end note
rdb ---[#Blue]--> rdb : Response
rdb ---[#Blue]--> rs : Response [200 ok]

@enduml
